import os
import sys
import subprocess

# On Windows, the path is incorrect, so change the path to
# the environment one. Even though windows is the problem,
# do it for all platforms

newpath=os.environ.get('PATH')
env = Environment(ENV = { 'PATH' : newpath })

#boost_libs = ['boost_program_options', 'boost_system']
#poker_eval = ['poker-eval']
env.Program('player', ['main.cpp', 'player.cpp','pbots_calc.c','util.c'], LIBS=['boost_program_options', 'boost_system','poker-eval'])
#env.SConscript(["SConscript"], exports='env')
